framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auto_setup: false

        routing:
            '*': async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
