# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    users_security_bundle_base_url: '%env(string:AUTHENTICATION_BASE_URL)%'
    users_security_bundle_public_pattern: '^/(status)|(health-check)'
    users_security_bundle_secured_pattern: '^/*'
    users_security_bundle_access_control_path: '^/*'
    message_delays:
        App\Message\StartWorkerJobMessage: '%env(int:START_WORKER_JOB_DELAY_MS)%'
        App\Message\GetSerializedSuiteStateMessage: '%env(int:SERIALIZED_SUITE_STATE_CHANGE_CHECK_PERIOD_MS)%'
        App\Message\MachineStateChangeCheckMessage: '%env(int:MACHINE_STATE_CHANGE_CHECK_PERIOD_MS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    Psr\Http\Client\ClientInterface:
        class: GuzzleHttp\Client

    GuzzleHttp\Psr7\HttpFactory: ~

    Psr\Http\Message\RequestFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\StreamFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    SmartAssert\ResultsClient\ResourceReferenceFactory: ~

    SmartAssert\ResultsClient\EventFactory: ~

    SmartAssert\ResultsClient\Client:
        arguments:
            $baseUrl: '%env(string:RESULTS_BASE_URL)%'

    SmartAssert\WorkerManagerClient\RequestFactory:
        arguments:
            $baseUrl: '%env(string:WORKER_MANAGER_BASE_URL)%'

    SmartAssert\WorkerManagerClient\Client: ~

    SmartAssert\SourcesClient\ExceptionFactory: ~

    SmartAssert\SourcesClient\SerializedSuiteFactory: ~

    SmartAssert\SourcesClient\RequestFactory:
        arguments:
            $baseUrl: '%env(string:SOURCES_BASE_URL)%'

    SmartAssert\SourcesClient\SerializedSuiteClient: ~

    SmartAssert\WorkerClient\ResourceReferenceFactory: ~

    SmartAssert\WorkerClient\EventFactory: ~

    SmartAssert\WorkerClient\TestFactory: ~

    SmartAssert\WorkerClient\JobFactory: ~

    App\Messenger\DelayMiddleware:
        arguments:
            $delays: '%message_delays%'
