name: dispatch.service-configure

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch service-configure event to instance manager
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.INSTANCE_MANAGER_TOKEN }}
          repository: smartassert/instance-manager
          event-type: service-configure
          client-payload: |
            {
              "service_id": "job-coordinator",
              "state_url": "http://{{ host }}/",
              "health_check_url": "http://{{ host }}/health-check"
            }
