name: dispatch.service-configure

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true

jobs:
  setup:
    name: Set service id
    runs-on: ubuntu-latest
    outputs:
      service_id: ${{ env.service_id }}

    steps:
      - name: Set env.service_id
        run: echo "service_id=job_coordinator" >> "$GITHUB_ENV"

  instance-manager-service-configure:
    needs: setup
    name: Dispatch service-configure event to instance manager
    runs-on: ubuntu-latest

    steps:
      -
        name: foo
        run: |
          echo "${{ needs.setup.outputs.service_id }}"

      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.INSTANCE_MANAGER_TOKEN }}
          repository: smartassert/instance-manager
          event-type: service-configure
          client-payload: |
            {
              "service_id": "${{ env.service_id }}",
              "state_url": "http://{{ host }}/status",
              "health_check_url": "http://{{ host }}/health-check"
            }

  instance-manager-service-set-env:
    name: Dispatch service-set-env event to instance manager
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set env.service_env_vars
        run: echo "service_env_vars=$(jq -R . < ./build/instance-manager/env.json | tr -d '\n' | sed 's/""//g')" >> "$GITHUB_ENV"

      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.INSTANCE_MANAGER_TOKEN }}
          repository: smartassert/instance-manager
          event-type: service-set-env
          client-payload: |
            {
              "service_id": "${{ env.service_id }}",
              "env_vars": ${{ env.service_env_vars }}
            }
